#-*- coding: UTF-8 -*-
print('hello world')
print('hello world')
print('hello world')
print('hello world')
#pdsdgsdfgsdfgsdfgrint('hello world')
print('hello world')
print('hello world')
print('hello world')
print('hello world')
print('hello world')
